### ISSUE TITLE
Nullability issue when deserializing embeds on message create

### ISSUE THREAD

**Issue by GiantTreeLP** [kordlib/kord#149]
Hi there,

I am using Kord and when receiving messages with embeds in them, the deserializer seems to require a field to be non-null, which seems to be nullable on Discord's end.

It seems as though an incorrect type in the documentation of Discord's API is to blame.
When deserializing the Provider of an embed, Discord does send a `null` value (in this case for the url), even though the documentation states, that the API will either send this field or not. It is not annotated to be nullable: https://discord.com/developers/docs/resources/channel#embed-object-embed-provider-structure

I have added the log of my bot below:

```
FINEST 2021-01-02T16:09:22.787+01:00 [dev.kord.gateway.DefaultGateway read]: Gateway <<< {"t":"MESSAGE_CREATE","s":3,"op":0,"d":{"type":0,"tts":false,"timestamp":"2021-01-02T15:09:22.288000+00:00","referenced_message":null,"pinned":false,"nonce":"794945439483822080","mentions":[],"mention_roles":[],"mention_everyone":false,"member":{"roles":["602449218765848576","595757090904211457","598614486810886145","559421263303540756","579389392867557400"],"premium_since":null,"pending":false,"nick":"GiantTree ðŸŒ³ðŸ�ª","mute":false,"joined_at":"2019-03-24T16:37:57.753000+00:00","is_pending":false,"hoisted_role":"559421263303540756","deaf":false},"id":"794945440084394004","flags":0,"embeds":[{"url":"https://www.reddit.com/r/pcmasterrace/comments/koep08/well_it_hapenned_to_me/","type":"link","title":"r/pcmasterrace - well it hapenned to me","thumbnail":{"width":1280,"url":"https://external-preview.redd.it/4Wx7Qk-RDRF92qFRVRroSbZJBd5fyc-NhYBaoeTxexI.png?format=pjpg&auto=webp&s=d8a739cfd37c84d714b8c44c49f441345ffd7719","proxy_url":"https://images-ext-2.discordapp.net/external/wo4g700-48jJTdXK2FXa61-w46oO7T_ZbcPCs0fP_Cw/%3Fformat%3Dpjpg%26auto%3Dwebp%26s%3Dd8a739cfd37c84d714b8c44c49f441345ffd7719/https/external-preview.redd.it/4Wx7Qk-RDRF92qFRVRroSbZJBd5fyc-NhYBaoeTxexI.png","height":720},"provider":{"url":null,"name":"reddit"},"description":"34,735 votes and 409 comments so far on Reddit","color":16777215}],"edited_timestamp":null,"content":"https://www.reddit.com/r/pcmasterrace/comments/koep08/well_it_hapenned_to_me/","channel_id":"565872054059008009","author":{"username":"GiantTree ðŸ�ª","public_flags":128,"id":"103595873841188864","discriminator":"1337","avatar":"6bd97d13e277373bb0c900b02dde064a"},"attachments":[],"guild_id":"559415621956141076"}}
SEVERE 2021-01-02T16:09:22.798+01:00 [io.ktor.util.LoggingKt error]: descriptor for kotlin.String was not nullable but null mark was encountered
kotlinx.serialization.SerializationException: descriptor for kotlin.String was not nullable but null mark was encountered
	at dev.kord.common.entity.optional.Optional$OptionalSerializer.deserialize(Optional.kt:160)
	at dev.kord.common.entity.optional.Optional$OptionalSerializer.deserialize(Optional.kt:151)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
	at dev.kord.common.entity.DiscordEmbed$Provider$$serializer.deserialize(DiscordMessage.kt)
	at dev.kord.common.entity.DiscordEmbed$Provider$$serializer.deserialize(DiscordMessage.kt:480)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at dev.kord.common.entity.optional.Optional$OptionalSerializer.deserialize(Optional.kt:173)
	at dev.kord.common.entity.optional.Optional$OptionalSerializer.deserialize(Optional.kt:151)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
	at dev.kord.common.entity.DiscordEmbed$$serializer.deserialize(DiscordMessage.kt)
	at dev.kord.common.entity.DiscordEmbed$$serializer.deserialize(DiscordMessage.kt:392)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:479)
	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
	at dev.kord.common.entity.DiscordMessage$$serializer.deserialize(DiscordMessage.kt)
	at dev.kord.common.entity.DiscordMessage$$serializer.deserialize(DiscordMessage.kt:63)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:479)
	at dev.kord.gateway.Event$Companion.getByDispatchEvent(Event.kt:132)
	at dev.kord.gateway.Event$Companion.deserialize(Event.kt:72)
	at dev.kord.gateway.Event$Companion.deserialize(Event.kt:39)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
	at dev.kord.gateway.DefaultGateway.read(DefaultGateway.kt:191)
	at dev.kord.gateway.DefaultGateway$readSocket$$inlined$collect$1.emit(Collect.kt:134)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:61)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

This issue prevents me from handling messages with embeds (i.e. due to embedded links) added to them at all.

**Comment by HopeBaron** [comment]
Thank you! We will look into this.
