### ISSUE TITLE
ClassCastException on new channel types

### ISSUE THREAD

**Issue by ArcheCraft** [kordlib/kord#300]
When calling `GuildBehavior.channels` and colleting the resulting `Flow`, and the guild contains one of the new channel types, it throws a `ClassCastException`:
`java.lang.ClassCastException: class dev.kord.core.entity.channel.Channel$Companion$from$1 cannot be cast to class dev.kord.core.entity.channel.GuildChannel`
Probably because the new channels aren't implemented and therefore are an anonymous `Channel`, which of course is not a `GuildChannel`.

**Comment by BartArys** [comment]
Thanks for reporting, this came to our attention a while ago but we seemed to have missed applying to fix to REST supplier as well.

**Comment by ArcheCraft** [comment]
The same problem appears with the cache

**Comment by BartArys** [comment]
Can you give me a stacktrace and the Kord version you're using? I'll look into it

**Comment by ArcheCraft** [comment]
I use "com.kotlindiscord.kord.extensions:kord-extensions:1.4.0-RC7", which (as far as i know) uses a snapshot version of kord.

Stacktrace:
Exception in thread "DefaultDispatcher-worker-8" java.lang.ClassCastException: class dev.kord.core.entity.channel.Channel$Companion$from$1 cannot be cast to class dev.kord.core.entity.channel.GuildChannel (dev.kord.core.entity.channel.Channel$Companion$from$1 and dev.kord.core.entity.channel.GuildChannel are in unnamed module of loader 'app')
	at dev.kord.core.supplier.CacheEntitySupplier$getGuildChannels$$inlined$map$1$2.emit(Collect.kt:135)
	at dev.kord.cache.map.internal.Action$ValueAction$onMap$$inlined$filter$1$2.emit(Collect.kt:135)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
	at dev.kord.cache.map.MapLikeCollection$Companion$from$1$values$1.invokeSuspend(MapLikeCollection.kt:89)
	at dev.kord.cache.map.MapLikeCollection$Companion$from$1$values$1.invoke(MapLikeCollection.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
	at dev.kord.cache.map.internal.Action$ValueAction$onMap$$inlined$filter$1.collect(SafeCollector.common.kt:114)
	at dev.kord.core.supplier.CacheEntitySupplier$getGuildChannels$$inlined$map$1.collect(SafeCollector.common.kt:114)
	at dev.kord.core.UtilKt$switchIfEmpty$1.invokeSuspend(Util.kt:294)
	at dev.kord.core.UtilKt$switchIfEmpty$1.invoke(Util.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
	at kotlinx.coroutines.flow.FlowKt__CollectionKt.toCollection(Collection.kt:32)
	at kotlinx.coroutines.flow.FlowKt.toCollection(Unknown Source)
	at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList(Collection.kt:15)
	at kotlinx.coroutines.flow.FlowKt.toList(Unknown Source)
	at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList$default(Collection.kt:15)
	at kotlinx.coroutines.flow.FlowKt.toList$default(Unknown Source)
	at com.archecraft.games.extensions.CLIExtension$setup$2$2$1$1.invokeSuspend(CLIExtension.kt:31)
	at com.archecraft.games.extensions.CLIExtension$setup$2$2$1$1.invoke(CLIExtension.kt)
	at com.archecraft.games.CLICommand.call(CLI.kt:47)
	at com.archecraft.games.CLICommand.call(CLI.kt:45)
	at com.archecraft.games.CLI.start(CLI.kt:28)
	at com.archecraft.games.CLIKt$cli$1.invokeSuspend(CLI.kt:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Also, if it helps, this is the code: https://github.com/ArcheCraft/ArchesDiscordBot

**Comment by BartArys** [comment]
kord-extensions:1.4.0-RC depends on a snaptshot from before the fix was applied (26 feb vs Apr13). This should be fixed (for cache at least) when the author updates their dependency and will be completely fixed in the next Kord release.

**Comment by gdude2002** [comment]
FTR, at least right now, users are encouraged to make use of the KordEx snapshots. I'll get another stable release out once Kord hits Kotlin 1.5.
