### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by AuukiXD** [kordlib/kord#77]
```
Stacktrace: 
Exception in thread "main" java.lang.NoSuchMethodError: java.io.ByteArrayOutputStream.toString(Ljava/nio/charset/Charset;)Ljava/lang/String;
	at com.gitlab.kordlib.gateway.DefaultGateway.deflateData(DefaultGateway.kt:185)
	at com.gitlab.kordlib.gateway.DefaultGateway.read(DefaultGateway.kt:191)
	at com.gitlab.kordlib.gateway.DefaultGateway$readSocket$$inlined$collect$1.emit(Collect.kt:134)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:73)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:55)
	at com.gitlab.kordlib.gateway.DefaultGateway$asFlow$1.invokeSuspend(DefaultGateway.kt:227)
	at com.gitlab.kordlib.gateway.DefaultGateway$asFlow$1.invoke(DefaultGateway.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:60)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:210)
	at com.gitlab.kordlib.gateway.DefaultGateway.readSocket(DefaultGateway.kt:351)
	at com.gitlab.kordlib.gateway.DefaultGateway$start$2.invokeSuspend(DefaultGateway.kt:128)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:243)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:199)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:68)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:149)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Process finished with exit code 1
```

**Comment by AuukiXD** [comment]
I have no idea what has caused this, all I have used is Kordx.commands & Kord... nothing else in the build.gradle.kts

**Comment by BartArys** [comment]
`ByteArrayOutputStream.toString` was introduced in Java 10.  It wasn't our intention to break Java 8 compatibility, we'll fix this in the next patch.
