### ISSUE TITLE
Nullability issue when getting application info

### ISSUE THREAD

**Issue by kotakotik22** [kordlib/kord#870]
Seems like this is exactly like #149, just for a different type and field.

<details>
<summary>Formatted JSON</summary>

```json
{
   "id":"851983047598538772",
   "name":"\u0422\u0443\u0440\u0435\u043b\u044c",
   "icon":null,
   "description":"",
   "type":null,
   "bot":{
      "id":"851983047598538772",
      "username":"\u0422\u0443\u0440\u0435\u043b\u044c",
      "avatar":"9c55261abc3e35ed59cfa5337843d6d6",
      "discriminator":"4161",
      "public_flags":0,
      "flags":0,
      "bot":true,
      "banner":null,
      "accent_color":null,
      "global_name":null,
      "avatar_decoration_data":null,
      "banner_color":null
   },
   "summary":"",
   "bot_public":false,
   "bot_require_code_grant":false,
   "verify_key":"SOMETHING",
   "flags":11051008,
   "hook":true,
   "is_monetized":false,
   "redirect_uris":[
      
   ],
   "interactions_endpoint_url":null,
   "role_connections_verification_url":null,
   "owner":{
      "id":"374319949352796161",
      "username":"kotakotik",
      "avatar":"d971c703e5af16c0f6d8e389dfe1f6ae",
      "discriminator":"0",
      "public_flags":768,
      "flags":768,
      "banner":null,
      "accent_color":null,
      "global_name":"Kota",
      "avatar_decoration_data":null,
      "banner_color":null
   },
   "approximate_guild_count":1,
   "interactions_event_types":[
      
   ],
   "interactions_version":1,
   "explicit_content_filter":0,
   "rpc_application_state":0,
   "store_application_state":1,
   "creator_monetization_state":1,
   "verification_state":1,
   "integration_public":false,
   "integration_require_code_grant":false,
   "discoverability_state":1,
   "discovery_eligibility_flags":2496,
   "monetization_state":1,
   "monetization_eligibility_flags":0,
   "team":null
}
```
</details>

```
[DefaultDispatcher-worker-11] DEBUG [R]:[KTOR]:[ExclusionRequestRateLimiter] - [RESPONSE]:200:GET:https://discord.com/api/v10/oauth2/applications/@me body:{"id":"851983047598538772","name":"\u0422\u0443\u0440\u0435\u043b\u044c","icon":null,"description":"","type":null,"bot":{"id":"851983047598538772","username":"\u0422\u0443\u0440\u0435\u043b\u044c","avatar":"9c55261abc3e35ed59cfa5337843d6d6","discriminator":"4161","public_flags":0,"flags":0,"bot":true,"banner":null,"accent_color":null,"global_name":null,"avatar_decoration_data":null,"banner_color":null},"summary":"","bot_public":false,"bot_require_code_grant":false,"verify_key":"SOMETHING","flags":11051008,"hook":true,"is_monetized":false,"redirect_uris":[],"interactions_endpoint_url":null,"role_connections_verification_url":null,"owner":{"id":"374319949352796161","username":"kotakotik","avatar":"d971c703e5af16c0f6d8e389dfe1f6ae","discriminator":"0","public_flags":768,"flags":768,"banner":null,"accent_color":null,"global_name":"Kota","avatar_decoration_data":null,"banner_color":null},"approximate_guild_count":1,"interactions_event_types":[],"interactions_version":1,"explicit_content_filter":0,"rpc_application_state":0,"store_application_state":1,"creator_monetization_state":1,"verification_state":1,"integration_public":false,"integration_require_code_grant":false,"discoverability_state":1,"discovery_eligibility_flags":2496,"monetization_state":1,"monetization_eligibility_flags":0,"team":null}

kotlinx.serialization.SerializationException: descriptor for kotlin.String was not nullable but null mark was encountered
	at dev.kord.common.entity.optional.Optional$OptionalSerializer.deserialize(Optional.kt:164)
	at dev.kord.common.entity.optional.Optional$OptionalSerializer.deserialize(Optional.kt:155)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
	at dev.kord.common.entity.DiscordApplication$$serializer.deserialize(DiscordApplication.kt:42)
	at dev.kord.common.entity.DiscordApplication$$serializer.deserialize(DiscordApplication.kt:42)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at dev.kord.rest.route.ValueJsonMapper.deserialize(Route.kt:24)
	at dev.kord.rest.request.KtorRequestHandler.handle(KtorRequestHandler.kt:68)
	at dev.kord.rest.request.KtorRequestHandler$handle$1.invokeSuspend(KtorRequestHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by lukellmann** [comment]
should be in `0.11.0-SNAPSHOT` and will be included in the next release
