### ISSUE TITLE
Unexpected null field when parsing audit log entry

### ISSUE THREAD

**Issue by nerd** [kordlib/kord#889]
seems like the `user_id` field can be null in some circumstances in an audit log entry, but Kord doesn't expect that. using Kord version 0.11.1.

```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1937: Failed to parse type 'ULong' for input 'null' at path: $.audit_log_entries[9].user_id
JSON input: .....action_type":25,"user_id":null,"target_id":"<redacted>.....
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
        at kotlinx.serialization.json.internal.JsonDecoderForUnsignedTypes.decodeLong(StreamingJsonDecoder.kt:406)
        at dev.kord.common.entity.Snowflake$Serializer.deserialize(Snowflake.kt:226)
        at dev.kord.common.entity.Snowflake$Serializer.deserialize(Snowflake.kt:222)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
        at dev.kord.common.entity.DiscordAuditLogEntry$$serializer.deserialize(AuditLog.kt:105)
        at dev.kord.common.entity.DiscordAuditLogEntry$$serializer.deserialize(AuditLog.kt:105)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
        at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:165)
        at dev.kord.common.entity.DiscordAuditLog$$serializer.deserialize(AuditLog.kt:91)
        at dev.kord.common.entity.DiscordAuditLog$$serializer.deserialize(AuditLog.kt:91)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
        at dev.kord.rest.route.ValueJsonMapper.deserialize(Route.kt:24)
        at dev.kord.rest.request.KtorRequestHandler.handle(KtorRequestHandler.kt:68)
        at dev.kord.rest.request.KtorRequestHandler$handle$1.invokeSuspend(KtorRequestHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)```

**Comment by lukellmann** [comment]
this has been fixed in #885 and will be included in the next release. you can use `0.12.0-SNAPSHOT` if you need the fix as soon as possible.
