### ISSUE TITLE
Setting presence crashes the bot

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [kordlib/kord#956]
```
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property socket has not been initialized
	at dev.kord.gateway.DefaultGateway.sendUnsafe(DefaultGateway.kt:280)
	at dev.kord.gateway.DefaultGateway.send(DefaultGateway.kt:263)
	at dev.kord.core.cache.CachingGateway.send(CachingGateway.kt)
	at dev.kord.core.gateway.MasterGateway$DefaultImpls.sendAll(MasterGateway.kt:36)
	at dev.kord.core.gateway.DefaultMasterGateway.sendAll(DefaultMasterGateway.kt:10)
```
This happens if you have any event when setting presence from `Kord.login {}`

**Comment by MrMasrozYTLIVE** [comment]
![image](https://github.com/kordlib/kord/assets/61359286/3e88d68f-38a3-4d55-8e72-07d240b4f12c)

**Comment by MrMasrozYTLIVE** [comment]
```Kotlin
kord.on<MessageCreateEvent> { // runs every time a message is created that our bot can read
            message.getChannel().createMessage("test")
        }

        kord.login {
            kord.editPresence {
                this.watching("Tsukimichi: Moonlit Fantasy")
                this.status = PresenceStatus.DoNotDisturb
            }
        }
  ```
This code is crashing, but if you either remove `Kord.on` (Happens with any event) or you remove `Kord.editPresence` then it works just fine

**Comment by DRSchlaubi** [comment]
You can't send gateway commands at this point, if you want to set a presence during login use the presence builder

```kotlin
kord.login {
  presence {
    watching("Tsukimichi: Moonlit Fantasy")
    status = PresenceStatus.DoNotDisturb
   }
}
